### PR TITLE
Don't pipe output to indent

### PR DESCRIPTION
**Pull request by trevorrjohn**

### CODE REVIEW

**Comment by seanpdoyle** [comment]
Don't pipe output to `indent`
    
    When installing many, many, (many) NPM packages, piping the output
    through `indent` can be too much for the dyno, and blocks the deploy.
    
    This commit removes all calls to `| indent`.

---

**Comment by geoffharcourt** [comment]
I think you want this to say "don't"?

**Comment by seanpdoyle** [comment]
LGTM

**Comment by seanpdoyle** [comment]
LGTM

**Pull request merged**
